name: prasflutterwidget
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6
  firebase_crashlytics: ^4.2.0
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.16
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  fluttertoast: ^8.2.8
  syncfusion_flutter_datepicker: ^26.2.13
  image_cropper: ^8.0.2
  intl: ^0.19.0
  get_it: ^8.0.2
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  dartz: ^0.10.1
  permission_handler: ^11.3.1
  bloc_concurrency: ^0.2.5
  flutter_downloader: ^1.11.8
  path_provider: ^2.1.5
  material_design_icons_flutter: ^7.0.7296
  shimmer: ^3.0.0
  file_picker: ^8.1.4
  fl_chart: ^0.69.2
  url_launcher: ^6.3.1
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  sizer: ^3.0.5
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_typeahead: ^5.2.0
  scroll_date_picker: ^3.8.0
  time_picker_spinner: ^1.0.0
  flutter_styled_toast: ^2.2.1
  scroll_to_index: ^3.0.1
  flutter_cupertino_datetime_picker: ^3.0.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  gmt: ^0.8.0
  timezone: ^0.10.0
  simple_gesture_detector: ^0.2.1
  flutter_html: ^3.0.0-beta.2
  google_maps_flutter_ios: ^2.13.2
  open_file_plus: ^3.4.1+1
  crypto: ^3.0.6
  package_info_plus: ^8.1.1
  uuid: ^4.5.1
  slide_countdown: ^2.0.2
  hand_signature: ^3.0.3
  app_settings: ^5.1.1
  flutter_native_splash: ^2.4.3
  collection: ^1.18.0
  flutter_jailbreak_detection: ^1.10.0
  custom_refresh_indicator: ^4.0.1
  new_version_plus: ^0.0.12

flutter_gen:
  line_length: 8000
  null_safety: true
  assets:
    outputs:
      package_parameter_enabled: true

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bitmap/
    - assets/vector/
